### ISSUE TITLE
Maybe MDS error?

### ISSUE THREAD

**Issue by AndroidBaaaby** [jasonwbw/DensityPeakCluster#4]
`UserWarning: The MDS API has changed.``fit``now constructs an dissimilarity matrix from data. To use a custom dissimilarity matrix, set``dissimilarity='precomputed'``.
  warnings.warn("The MDS API has changed.``fit``now constructs an"
INFO : PLOT: end mds, start plot
F:\github_download\Clustering by fast search and find of density peaks\DensityPeakCluster-master\plot_utils.py:22: FutureWarning: comparison to`None`will result in an elementwise object comparison in the future.
  if style_list != None:
Traceback (most recent call last):
  File "F:/github_download/Clustering by fast search and find of density peaks/DensityPeakCluster-master/step2_cluster.py", line 20, in <module>
    plot('./data/data_iris_flower/iris.forcluster', 40, 0.80624, auto_select_dc = True)
  File "F:/github_download/Clustering by fast search and find of density peaks/DensityPeakCluster-master/step2_cluster.py", line 16, in plot
    plot_cluster(dpcluster)
  File "F:\github_download\Clustering by fast search and find of density peaks\DensityPeakCluster-master\plot.py", line 45, in plot_cluster
    plot_scatter_diagram(1, dp_mds[:, 0], dp_mds[:, 1], title='cluster', style_list = cls)
  File "F:\github_download\Clustering by fast search and find of density peaks\DensityPeakCluster-master\plot_utils.py", line 23, in plot_scatter_diagram
    assert len(x) == len(style_list) and len(styles) >= len(set(style_list))
AssertionError`

When ran the step2.py, I got those problems. I'm not sure whether it's a mds error as @liuguiyangnwpu met. 
Thank you.

**Comment by jasonwbw** [comment]
#3 maybe you can reference this issue.

**Comment by jasonwbw** [comment]
I think you have not change the interface like his.

This is what he mentioned about,

mds = manifold.MDS(max_iter=200, eps=1e-4, n_init=1,dissimilarity="precomputed")
#mds = manifold.MDS(max_iter=200, eps=1e-4, n_init=1)

**Comment by AndroidBaaaby** [comment]
I have changed the interface like #3, but the problem is still unsovled. If i replace the code `       
 if X.shape[0] == X.shape[1] and self.dissimilarity != "precomputed":
            warnings.warn("The MDS API has changed. ``fit`` now constructs an"
                          " dissimilarity matrix from data. To use a custom "
                          "dissimilarity matrix, set "
                          "``dissimilarity='precomputed'``.")` 
with `mds = manifold.MDS(max_iter=200, eps=1e-4, n_init=1,dissimilarity="precomputed")`,  the new problem is `global name 'manifold' is not defined`.
By searching in stackflow, they said the version may be the problem. I'm not a python-learner, so i can't find out the problem on my own. 
According to what you wrote  in readme.md,  the cluster result can be got by running step1 and step 2. If i download your code and install all the needed dependencies, can i run the project directly?
Thank you for answering me. (●'◡'●)ﾉ♥

**Comment by jasonwbw** [comment]
Fixed in the current version. you can make it work by sklearn version 0.18, and sorry for the late response.
