### ISSUE TITLE
A numerical bug in cluster.py

### ISSUE THREAD

**Issue by yaox12** [jasonwbw/DensityPeakCluster#5]
line 79 in [cluster.py](https://github.com/jasonwbw/DensityPeakCluster/blob/master/cluster.py#L79)
`if nneighs >= 0.01 and nneighs <= 0.002:`

I suppose it should be `if nneighs >= 0.01 and nneighs <= 0.02:`

0.02 instead of 0.002

**Comment by jasonwbw** [comment]
I think you are right, already fixed. Thanks.
