### ISSUE TITLE
Error while checking sklearn version

### ISSUE THREAD

**Issue by menisadi** [jasonwbw/DensityPeakCluster#7]
On plot.py line 46 when checking 
if float(sklearn_version) > 0.14:
got Error because sklearn_version='0.17.1' and as such can't be converted to float
I suggest changing to 
float(sklearn_version[:4]) > 0.14

**Comment by gwdgithubnom** [comment]
I had changed this problem by using str function.

**Comment by scaactk** [comment]
@menisadi  I have solved the problems with your solution , thanks

**Comment by jasonwbw** [comment]
@menisadi OK, thanks for your suggestions, and I have fixed it.  0b5b8e24969b04a23730605a61391cd74485989a
